# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 798)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-30, 0, 251, 801))
        self.widget.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"border-radius: 32px;")
        self.widget.setObjectName("widget")
        self.hair = QtWidgets.QPushButton(self.widget)
        self.hair.setGeometry(QtCore.QRect(50, 160, 61, 60))
        self.hair.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;\n"
"\n"
"")
        self.hair.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/hair.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hair.setIcon(icon)
        self.hair.setIconSize(QtCore.QSize(32, 32))
        self.hair.setObjectName("hair")
        self.text = QtWidgets.QLabel(self.widget)
        self.text.setGeometry(QtCore.QRect(70, 50, 121, 51))
        self.text.setStyleSheet("font: italic 16pt \"Sitka Small\";")
        self.text.setObjectName("text")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 180, 101, 21))
        self.label.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 240, 60, 60))
        self.pushButton_4.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open-mail-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(52, 52))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(120, 260, 71, 31))
        self.label_4.setStyleSheet("font: 13pt \"Mongolian Baiti\";")
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(270, 260, 741, 481))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 13px;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 202, 101, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "FlowersSPA"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Запись"))
        self.label_4.setText(_translate("MainWindow", "DB"))
        self.pushButton.setText(_translate("MainWindow", "Обновить записи"))
import res_rc
