# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hair.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 798)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-30, 0, 251, 801))
        self.widget.setStyleSheet("background-color: rgb(100, 100, 100);\n"
"border-radius: 32px;")
        self.widget.setObjectName("widget")
        self.hair = QtWidgets.QPushButton(self.widget)
        self.hair.setGeometry(QtCore.QRect(50, 160, 61, 60))
        self.hair.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;\n"
"\n"
"")
        self.hair.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/hair.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hair.setIcon(icon)
        self.hair.setIconSize(QtCore.QSize(32, 32))
        self.hair.setObjectName("hair")
        self.text = QtWidgets.QLabel(self.widget)
        self.text.setGeometry(QtCore.QRect(70, 50, 121, 51))
        self.text.setStyleSheet("font: italic 16pt \"Sitka Small\";")
        self.text.setObjectName("text")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 180, 101, 21))
        self.label.setStyleSheet("font: 9pt \"Mongolian Baiti\";")
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 240, 60, 60))
        self.pushButton_4.setStyleSheet("border: 3px solid rbg(0, 0, 0);\n"
"border-radius: 4px;")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open-mail-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(52, 52))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(120, 260, 71, 31))
        self.label_4.setStyleSheet("font: 13pt \"Mongolian Baiti\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 60, 111, 111))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 52px;")
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/0416856-round.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 100, 251, 31))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 12pt \"Sitka Display\";\n"
"border-radius: 4px;")
        self.label_6.setObjectName("label_6")
        self.olga_combo = QtWidgets.QComboBox(self.centralwidget)
        self.olga_combo.setGeometry(QtCore.QRect(700, 100, 131, 31))
        self.olga_combo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"font: italic 12pt \"Sitka Display\";")
        self.olga_combo.setObjectName("olga_combo")
        self.olga_combo.addItem("")
        self.olga_combo.addItem("")
        self.olga_combo.addItem("")
        self.olga_combo.addItem("")
        self.olga_combo.addItem("")
        self.olga_combo.addItem("")
        self.olga_combo.addItem("")
        self.olga_alina = QtWidgets.QPushButton(self.centralwidget)
        self.olga_alina.setGeometry(QtCore.QRect(870, 100, 111, 31))
        self.olga_alina.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 4px;\n"
"font: italic 12pt \"Sitka Display\";\n"
"")
        self.olga_alina.setObjectName("olga_alina")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 230, 111, 111))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 52px;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/devuska-goluboglazaa-volosay-round.png"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(420, 270, 271, 31))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 12pt \"Sitka Display\";\n"
"border-radius: 4px;")
        self.label_8.setObjectName("label_8")
        self.olga_combo_2 = QtWidgets.QComboBox(self.centralwidget)
        self.olga_combo_2.setGeometry(QtCore.QRect(700, 270, 131, 31))
        self.olga_combo_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"font: italic 12pt \"Sitka Display\";")
        self.olga_combo_2.setObjectName("olga_combo_2")
        self.olga_combo_2.addItem("")
        self.olga_combo_2.addItem("")
        self.olga_combo_2.addItem("")
        self.olga_combo_2.addItem("")
        self.olga_combo_2.addItem("")
        self.olga_combo_2.addItem("")
        self.olga_combo_2.addItem("")
        self.olga_alina_2 = QtWidgets.QPushButton(self.centralwidget)
        self.olga_alina_2.setGeometry(QtCore.QRect(870, 270, 111, 31))
        self.olga_alina_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 4px;\n"
"font: italic 12pt \"Sitka Display\";\n"
"")
        self.olga_alina_2.setObjectName("olga_alina_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(280, 390, 111, 111))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 52px;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/icons/milashka-rubashka-prelest-round.png"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(420, 430, 251, 31))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 12pt \"Sitka Display\";\n"
"border-radius: 4px;")
        self.label_10.setObjectName("label_10")
        self.olga_combo_3 = QtWidgets.QComboBox(self.centralwidget)
        self.olga_combo_3.setGeometry(QtCore.QRect(700, 430, 131, 31))
        self.olga_combo_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"font: italic 12pt \"Sitka Display\";")
        self.olga_combo_3.setObjectName("olga_combo_3")
        self.olga_combo_3.addItem("")
        self.olga_combo_3.addItem("")
        self.olga_combo_3.addItem("")
        self.olga_combo_3.addItem("")
        self.olga_combo_3.addItem("")
        self.olga_combo_3.addItem("")
        self.olga_combo_3.addItem("")
        self.olga_alina_3 = QtWidgets.QPushButton(self.centralwidget)
        self.olga_alina_3.setGeometry(QtCore.QRect(870, 430, 111, 31))
        self.olga_alina_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 4px;\n"
"font: italic 12pt \"Sitka Display\";\n"
"")
        self.olga_alina_3.setObjectName("olga_alina_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(280, 560, 111, 111))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 52px;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/icons/vzglyad-devushki-s-shikarnoj-vneshnostyu-round.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(420, 600, 251, 31))
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Sitka Display\";\n"
"border-radius: 4px;")
        self.label_12.setObjectName("label_12")
        self.olga_combo_4 = QtWidgets.QComboBox(self.centralwidget)
        self.olga_combo_4.setGeometry(QtCore.QRect(700, 600, 131, 31))
        self.olga_combo_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:4px;\n"
"font: italic 12pt \"Sitka Display\";")
        self.olga_combo_4.setObjectName("olga_combo_4")
        self.olga_combo_4.addItem("")
        self.olga_combo_4.addItem("")
        self.olga_combo_4.addItem("")
        self.olga_combo_4.addItem("")
        self.olga_combo_4.addItem("")
        self.olga_combo_4.addItem("")
        self.olga_combo_4.addItem("")
        self.olga_alina_4 = QtWidgets.QPushButton(self.centralwidget)
        self.olga_alina_4.setGeometry(QtCore.QRect(870, 600, 111, 31))
        self.olga_alina_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 4px;\n"
"font: italic 12pt \"Sitka Display\";\n"
"")
        self.olga_alina_4.setObjectName("olga_alina_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "FlowersSPA"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Запись"))
        self.label_4.setText(_translate("MainWindow", "DB"))
        self.label_6.setText(_translate("MainWindow", "Массажист Олег, 6 лет опыта"))
        self.olga_combo.setItemText(0, _translate("MainWindow", "9:00"))
        self.olga_combo.setItemText(1, _translate("MainWindow", "11:00"))
        self.olga_combo.setItemText(2, _translate("MainWindow", "13:00"))
        self.olga_combo.setItemText(3, _translate("MainWindow", "15:00"))
        self.olga_combo.setItemText(4, _translate("MainWindow", "17:00"))
        self.olga_combo.setItemText(5, _translate("MainWindow", "19:00"))
        self.olga_combo.setItemText(6, _translate("MainWindow", "21:00"))
        self.olga_alina.setText(_translate("MainWindow", "Записаться"))
        self.label_8.setText(_translate("MainWindow", " Парикмахер Ольга, стаж работы 4 года, 25 лет"))
        self.olga_combo_2.setItemText(0, _translate("MainWindow", "9:00"))
        self.olga_combo_2.setItemText(1, _translate("MainWindow", "11:00"))
        self.olga_combo_2.setItemText(2, _translate("MainWindow", "13:00"))
        self.olga_combo_2.setItemText(3, _translate("MainWindow", "15:00"))
        self.olga_combo_2.setItemText(4, _translate("MainWindow", "17:00"))
        self.olga_combo_2.setItemText(5, _translate("MainWindow", "19:00"))
        self.olga_combo_2.setItemText(6, _translate("MainWindow", "21:00"))
        self.olga_alina_2.setText(_translate("MainWindow", "Записаться"))
        self.label_10.setText(_translate("MainWindow", "Визажист Дарья, 10 лет опыта"))
        self.olga_combo_3.setItemText(0, _translate("MainWindow", "9:00"))
        self.olga_combo_3.setItemText(1, _translate("MainWindow", "11:00"))
        self.olga_combo_3.setItemText(2, _translate("MainWindow", "13:00"))
        self.olga_combo_3.setItemText(3, _translate("MainWindow", "15:00"))
        self.olga_combo_3.setItemText(4, _translate("MainWindow", "17:00"))
        self.olga_combo_3.setItemText(5, _translate("MainWindow", "19:00"))
        self.olga_combo_3.setItemText(6, _translate("MainWindow", "21:00"))
        self.olga_alina_3.setText(_translate("MainWindow", "Записаться"))
        self.label_12.setText(_translate("MainWindow", "Мастер маникюра Виктория, стаж 3 года"))
        self.olga_combo_4.setItemText(0, _translate("MainWindow", "9:00"))
        self.olga_combo_4.setItemText(1, _translate("MainWindow", "11:00"))
        self.olga_combo_4.setItemText(2, _translate("MainWindow", "13:00"))
        self.olga_combo_4.setItemText(3, _translate("MainWindow", "15:00"))
        self.olga_combo_4.setItemText(4, _translate("MainWindow", "17:00"))
        self.olga_combo_4.setItemText(5, _translate("MainWindow", "19:00"))
        self.olga_combo_4.setItemText(6, _translate("MainWindow", "21:00"))
        self.olga_alina_4.setText(_translate("MainWindow", "Записаться"))
import res_rc
